references:

  defaults: &defaults
    working_directory: ~/sp-ui-ts
    docker:
      - image: circleci/node:8

  npm_restore_cache: &npm_restore_cache
    restore_cache:
      key: dependency-cache-{{checksum "package.json" }}

  npm_setup_dependencies: &npm_setup_dependencies
    run:
      name: Setup Dependencies
      command: npm install
  
  npm_build_static_file_project: &npm_build_static_file_project
    run:
      name: Build static file project
      command: npm run clean:static && npm run build

  npm_run_test: &npm_run_test
    run: # run tests
      name: Run Test
      command: npm run test
      

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *npm_restore_cache
      - <<: *npm_setup_dependencies
      - <<: *npm_build_static_file_project
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - <<: *npm_restore_cache
      - <<: *npm_run_test
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - development
      - test:
          requires:
            - build