version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: #special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Build static file project
          command: npm run clean:static && npm run build
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: #special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json" }}
      - run: # run tests
          name: Run Test
          command: npm run test
workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - test:
        requires:
          - build